### ISSUE TITLE
CATFIN for every firm

### ISSUE THREAD

**Issue by NicuSV** [TommasoBelluzzo/SystemicRisk#10]
Dear Tommaso,

It is possible to adjust the code to diplay the results in a excel file for CATFIN, Absorbtion Ratio and Turbulence index for every firm in part, not the average for the whole sample?

Thanks!

**Comment by TommasoBelluzzo** [comment]
Dear Nicu, I don't think it's possible to do what you ask for. At least not for all the measures. Let's take the absorption ratio, which is defined as the fraction variance of a set of assets explained by a specific number of eigenvectors. How should that look like when applied to a vector of observations?

**Comment by NicuSV** [comment]
@TommasoBelluzzo,
Sorry, the question should have been stated in terms of "possible measures".
Thanks.

**Comment by TommasoBelluzzo** [comment]
I think that only CATFIN can be run on single names. And I can totally handle that. No idea how much time it will take, though. Depends on my workload actually.

**Comment by NicuSV** [comment]
@TommasoBelluzzo,
Nice work, thanks again for your readiness to help.
Cheers!

Nicu

**Comment by TommasoBelluzzo** [comment]
Hi Nicu, I tried to implement that but there are some major issues:
- the code has become too slow, actually one of the slowest frameworks of the package;
- there are problems handling defaulted firms and sequential plots.

For the moment, I close this request and I suggest you to dissect my code to obtain what you are looking for.
I'll try to undertake that in the future but for the moment is not really a priority in the context of measuring systemic risk.

Best, Tommaso
