### ISSUE TITLE
The set of parameters

### ISSUE THREAD

**Issue by DF-18** [TommasoBelluzzo/SystemicRisk#14]
Dear  Tommaso,

May I ask some questions about the parameters setting?

The description of input parameters in run_cross_sectional.m is as below.

```
% [INPUT]
% ds = A structure representing the dataset.
% sn = A string representing the serial number of the result file.
% temp = A string representing the full path to the Excel spreadsheet used as template for the result file.
% out = A string representing the full path to the Excel spreadsheet to which the results are written, eventually replacing the previous ones.
% k = A float [0.90,0.99] representing the confidence level (optional, default=0.95).
% d = A float [0.1,0.6] representing the six-month crisis threshold for the market index decline used to calculate the LRMES (optional, default=0.4).
% car = A float [0.03,0.20] representing the capital adequacy ratio used to calculate SES and SRISK (optional, default=0.08).
% sf = A float [0,1] representing the fraction of separate accounts, if available, to include in liabilities and used to calculate SES and SRISK (optional, default=0.40).
% fr = An integer [0,6] representing the number of months of forward-rolling used to calculate the SRISK, simulating the difficulty of renegotiating debt in case of financial distress (optional, default=3).
% analyze = A boolean that indicates whether to analyse the results and display plots (optional, default=false).
%
```

The two questions related are:
 
1. Brownlees and Engle(2016) assumed the liabilities of the firm is non-negotiable. Under this kind of set, does it mean to set the 'fr' parameter to zero?

2. Since 'd' represents the six-month crisis threshold, how could I change the horizontal period from 'six-month' to, like 'one-month' or 'three-month'?

Thanks a lot.

**Comment by TommasoBelluzzo** [comment]
Hi!

1. Rolling forward the values means exactly that: liabilities are non-negotiable... better to say it's harder to renegotiate debt. Therefore, as the value of the parameter increases, the renegotiability of debt becomes harder. Setting the parameter value to 0, on the other hand, means there is a normal situation of negotiability.

1. The "six-month" part is a leftover. The parameter is just the crisis threshold, unrelated to any temporal frequency. So there is no horizon to adjust, but you can raise or lower it as you prefer.
