### ISSUE TITLE
Question about MES computation

### ISSUE THREAD

**Issue by suzy-p** [TommasoBelluzzo/SystemicRisk#17]
Hi Tommaso,
In SystemicRisk/ScriptsModels/connectedness_metrics.m, in order to compute the MES, you wrote the following 2 lines of code that I didn't fully understand the reasoning behind it. 

 r0_n = 4 / (3 * length(rm_0));
...
h = r0_s * r0_n ^0.2;

Is this explained in any research paper/ book?

Moreover, are you somehow replicating the following formula to obtain the ES and then compute the MES?

![Formula SE](https://user-images.githubusercontent.com/82149602/114018456-8975fb80-986d-11eb-8297-e4a74f78f346.jpg)

I'm really confused.
Thank you,
Suzy

**Comment by TommasoBelluzzo** [comment]
Hi Suzy, sorry for the belated reply. In my package I'm using one of the oldest MES formulations, focused on non-parametric kernel estimation of tail expectations as described in this paper (p. 15): https://faculty.washington.edu/ezivot/econ589/VolatilityBrownlees.pdf

Best regards,
Tommaso
