### ISSUE TITLE
Question about CoVaR computation

### ISSUE THREAD

**Issue by Liyang-Guo** [TommasoBelluzzo/SystemicRisk#19]
Hi Tommaso,

Thanks for the amazing works, the toolbox is quite useful！
And I‘m really confused about the output of CROSS-SECTIONAL MEASURES. CoVaR computation requires the coefficients estimates through quantile regression, b = quantile_regression(y,x,a), how to get the estimation results of the coefficient "b"? 

Best regards,
Guo

**Comment by TommasoBelluzzo** [comment]
Hi @Liyang-Guo, sorry for the belated reply.
Please, take a look at: https://github.com/TommasoBelluzzo/SystemicRisk/blob/013aa57eecb902638814810570f86a8e51833d70/ScriptsModels/cross_sectional_metrics.m#L140
