### ISSUE TITLE
run error again

### ISSUE THREAD

**Issue by wangyazhao001** [TommasoBelluzzo/SystemicRisk#5]
Hi,brother! When I run your code with my datas,there is a error :
 
错误使用 parallel.FevalFuture/fetchNext (line 217)
The function evaluation completed with an error.

出错 run_spillover>run_spillover_internal (line 76)
            [future_index,value] = fetchNext(futures);

出错 run_spillover (line 40)
    result =
    run_spillover_internal(data,out_temp,out_file,ipr.rw_bandwidth,ipr.rw_steps,rw_indices,ipr.lags,ipr.h,ipr.generalized,ipr.analyze);

出错 run (line 90)
result_spillover = run_spillover(data,out_temp_spillover,out_file_spillover,252,10,2,4,true,true);

原因:
    错误使用 mvregress (line 456)
    Covariance is not positive-definite.

So I think you haven't completely solved the problem with this——[future_index,value] = fetchNext(futures);

Sincerely hope you can solve this problem！

Here is my data in Baidu Web Disk！

链接：https://pan.baidu.com/s/122a0i6PQsqe0Jv9YCnMHcQ 
提取码：4f0f

**Comment by wangyazhao001** [comment]
Or I can email the datas to you if I have your email!

**Comment by wangyazhao001** [comment]
[Uploading Example_Large_mine.xlsx…]()

**Comment by wangyazhao001** [comment]
[Example_Large_mine.xlsx](https://github.com/TommasoBelluzzo/SystemicRisk/files/4148780/Example_Large_mine.xlsx)
This is my datas!

**Comment by TommasoBelluzzo** [comment]
Aw, this one is even more subtle than the previous one. Sorry for the inconvenience, I'm going to fix this asap.

**Comment by wangyazhao001** [comment]
> Aw, this one is even more subtle than the previous one. Sorry for the inconvenience, I'm going to fix this asap. Can you kindly provide me the parameters you use to run the spillovers function?

When running this error with my data, I did not change your parameters, so all parameters are your default parameters！
Sincerely hope you can solve this problem！Thank you very much！

**Comment by TommasoBelluzzo** [comment]
Hi Wang, I pushed another release. It contains major improvements and also a potential fix for your issue. It was not possible for me to test your dataset on my laptop because it's too huge and it was taking forever, but I know where the problem can arise and hopefully my modifications will prevent the error.
If this happens again, feel free to report back to me but in that case I'll need your help to replicate the issue in your data. In fact, we will eventually need to detect the rolling window in which the issue arises, store it somewhere and run the variance decomposition against it over and over until we find how to solve.

**Comment by wangyazhao001** [comment]
> Hi Wang, I pushed another release. It contains major improvements and also a potential fix for your issue. It was not possible for me to test your dataset on my laptop because it's too huge and it was taking forever, but I know where the problem can arise and hopefully my modifications will prevent the error.
> If this happens again, feel free to report back to me but in that case I'll need your help to replicate the issue in your data. In fact, we will eventually need to detect the rolling window in which the issue arises, store it somewhere and run the variance decomposition against it over and over until we find how to solve.

Thanks you very much!Let me test this codes first. I will let you the result later.

**Comment by TommasoBelluzzo** [comment]
Hi Wang, are you still experiencing this issue?

**Comment by wangyazhao001** [comment]
> Hi Wang, are you still experiencing this issue?
Sorry, my computer was broken. I bought a new computer in the past two days, so I didn't do the experiment in time. I'm very sorry. Last night I used your modified code to test five sets of data, and I can get the results I need, which shows that your code is correct absolutely. Thanks you very much!

**Comment by wangyazhao001** [comment]
> Hi Wang, are you still experiencing this issue?

Sorry, my computer was broken. I bought a new computer in the past two days, so I didn't do the experiment in time. I'm very sorry. Last night I used your modified code to test five sets of data, and I can get the results I need, which shows that your code is correct absolutely. Thanks you very much!

**Comment by wangyazhao001** [comment]
> Hi Wang, are you still experiencing this issue?

Sorry, my computer was broken. I bought a new computer in the past two days, so I didn't do the experiment in time. I'm very sorry. Last night I used your modified code to test five sets of data, and I can get the results I need, which shows that you fixed the error and your code is correct absolutely now. Thanks you very much!

**Comment by TommasoBelluzzo** [comment]
That sounds great. On a totally unrelated side note, do you have an e-mail address I can contact you with? I would like to ask you a few things about the project itself.

**Comment by NicuSV** [comment]
Hi, Tommaso,

There is a nice application of cross-quantilogram (Han et al., 2016) to systemic risk. You think it's possible to adapt the R code to Matlab? See https://sites.google.com/site/whangyjhomepage/research/software.
Thanks.

**Comment by TommasoBelluzzo** [comment]
Duplicate of #4
