### ISSUE TITLE
Another question——Add a new feature

### ISSUE THREAD

**Issue by wangyazhao001** [TommasoBelluzzo/SystemicRisk#6]
<img width="530" alt="realtionship_photo" src="https://user-images.githubusercontent.com/33176025/73668237-8ec33d80-46e0-11ea-970f-0fb9a47e8026.png">

Hello there! brothers! The picture shows the interconnections between so many companies. What if I just want to draw a diagram of the correlation between these four industries?

**Comment by TommasoBelluzzo** [comment]
Hi Wang. Creating a new plot is not really a big deal. The problem is: how do you define the correlation between the different sectors?

**Comment by wangyazhao001** [comment]
> Hi Wang. Creating a new plot is not really a big deal. The problem is: how do you define the correlation between the different sectors?

Oh! It was I who didn't figure out the concept at first. I have benefited a lot from your words. Thank you very much!
Another question——According to your code, I can see that spillover is calculated based on var，did you?

**Comment by TommasoBelluzzo** [comment]
Yes, spillovers are calculated, as per original formulation of D&Y, using the vector autoregression model.
