### ISSUE TITLE
spillover question

### ISSUE THREAD

**Issue by wangyazhao001** [TommasoBelluzzo/SystemicRisk#7]
Hello,brothers! Maybe last time I didn't express my question clearly. I know that spillover is calculated using vector autoregression model. What I want to ask is that  spillover is calculated based on  which parameter ? Is it calculated by var, covar, mes or other parameters?I can hardly see it in the code.Thank you very much!

**Comment by TommasoBelluzzo** [comment]
It has nothing to do with other measures.
