### ISSUE TITLE
Cross-Quantilogram Implementation

### ISSUE THREAD

**Issue by TommasoBelluzzo** [TommasoBelluzzo/SystemicRisk#8]
Hi, Tommaso,

There is a nice application of cross-quantilogram (Han et al., 2016) to systemic risk. You think it's possible to adapt the R code to Matlab? See https://sites.google.com/site/whangyjhomepage/research/software.
Thanks.

_Originally posted by @NicuSV in https://github.com/TommasoBelluzzo/SystemicRisk/issues/5#issuecomment-590282384_

**Comment by TommasoBelluzzo** [comment]
Hi @NicusSV, thanks for sharing that nice paper. Converting R code to MATLAB is not hard at all, but I've never heard about those systemic risk measures before. Therefore, before proceeding, I have to read the paper and understand how the framework is supposed to behave.

**Comment by NicuSV** [comment]
@TommasoBelluzzo, that would be great.
Initially, the authors developed the Quantilogram (Linton and Whang, 2007) for univariate analysis, and after this they took it to a bivariate framework, i.e., the Cross-Quantilogram (Han et al., 2016). It would be nice if you could implement both.
Cheers!

**Comment by TommasoBelluzzo** [comment]
Looks like it's done.

**Comment by NicuSV** [comment]
Great!
Thanks a lot, Tommaso!
Cheers!
