### ISSUE TITLE
Typo in calculate_mes bandwidth 

### ISSUE THREAD

**Issue by modigzd** [TommasoBelluzzo/SystemicRisk#9]
Within the `calculate_mes` function in the run_cross_sectional.m file, the current bandwidth for the kernel density estimator appears to be based on the Silverman "rule-of-thumb bandwidth estimator":

```
    r0_n = 4 / (3 * length(r0_m));
    r0_s = min([std(r0_m) (iqr(r0_m) / 1.349)]);
    h = r0_s * (r0_n ^ (-0.2));
```

However, I believe that the exponent is incorrect. I believe the formula for h should actually be:

```
    h = r0_s * (r0_n ^ (0.2));
```

See https://link.springer.com/chapter/10.1007/978-3-030-16272-6_3#Sec11 Section 5.5.

In addition I believe that you may want to scale r0_s by the conditonal market volatility, as everything else within the kernel density estimate is scaled. That is I believe this line:

```
    r0_s = min([std(r0_m) (iqr(r0_m) / 1.349)]);
```
Should actually be: 

```
    r0_s = min([std(r0_m ./ s_m) (iqr(r0_m ./ s_m) / 1.349)]);
```

When using actual P&L, if you don't scale `r0_s` by `s_m`, the value of `h` will be proportional to the standard deviation of the P&L. Practically, this will mean that for the value of `f` will be approximately .5 as `(c ./ s_m) - u)` divided by some very large number will converge to approximately 0, since `(c ./ s_m) - u)` should always be on the scale of approximately -10 to 10.

**Comment by TommasoBelluzzo** [comment]
Hi @modigzd, the issue should be fixed with the new release as of today. Thank you very much for your contribution, do not hesitate to contact me if you spot other issues!

Tommaso
